# Generated by Django 4.0.1 on 2022-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='顔写真')),
            ],
        ),
    ]
