# Generated by Django 4.0.1 on 2022-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='after',
            name='intro_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='顔写真'),
        ),
    ]
