# Generated by Django 4.0.1 on 2022-01-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真１'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='title',
            field=models.TextField(max_length=40, verbose_name='タイトル'),
        ),
    ]
